package br.com.arthiviatech.myfinances.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF005AC1)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD8E2FF)
val LightOnPrimaryContainer = Color(0xFF001A41)
val LightSecondary = Color(0xFF9C4400)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDBC8)
val LightOnSecondaryContainer = Color(0xFF341100)
val LightBackground = Color(0xFFFAF8FF)
val LightOnBackground = Color(0xFF1A1B20)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1A1B20)
val LightSurfaceVariant = Color(0xFFE1E2EC)
val LightOnSurfaceVariant = Color(0xFF44474F)
val LightOutline = Color(0xFF74777F)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

val DarkPrimary = Color(0xFFADC7FF)
val DarkOnPrimary = Color(0xFF002F67)
val DarkPrimaryContainer = Color(0xFF00458F)
val DarkOnPrimaryContainer = Color(0xFFD8E2FF)
val DarkSecondary = Color(0xFFFFB68F)
val DarkOnSecondary = Color(0xFF552100)
val DarkSecondaryContainer = Color(0xFF783200)
val DarkOnSecondaryContainer = Color(0xFFFFDBC8)
val DarkBackground = Color(0xFF111318)
val DarkOnBackground = Color(0xFFE2E2E9)
val DarkSurface = Color(0xFF191C20)
val DarkOnSurface = Color(0xFFE2E2E9)
val DarkSurfaceVariant = Color(0xFF44474F)
val DarkOnSurfaceVariant = Color(0xFFC4C6D0)
val DarkOutline = Color(0xFF8E9099)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
